default :
	${MAKE} -C fat
	${MAKE} -C vfs

tex :
	${MAKE} -C fat tex
	${MAKE} -C vfs tex

clean :
	${MAKE} -C fat clean
	${MAKE} -C vfs clean
	
depclean :
	${MAKE} -C fat depclean
	${MAKE} -C vfs depclean
