default :
	@$(MAKE) -C floppy
	@$(MAKE) -C keyboard
	@$(MAKE) -C manager

tex :
	@$(MAKE) -C floppy tex
	@$(MAKE) -C keyboard tex
	@$(MAKE) -C manager tex

depclean :
	@$(MAKE) -C floppy depclean
	@$(MAKE) -C keyboard depclean
	@$(MAKE) -C manager depclean

clean :
	@$(MAKE) -C floppy clean
	@$(MAKE) -C keyboard clean
	@$(MAKE) -C manager clean
