default :
	cd floppy; make
	cd keyboard; make
	cd manager; make

depclean :
	cd floppy; make depclean
	cd keyboard; make depclean
	cd manager; make depclean

clean :
	cd floppy; make clean
	cd keyboard; make clean
	cd manager; make clean
