
default :  shell.app

shell.app :
	@$(MAKE) -s -C shell
	@echo
	@echo "#######################################"
	@echo "Built user applications: shell.app"
	@echo "#######################################"
	@echo

clean :
	@$(MAKE) -C shell clean
	@rm -f shell.app
