C_SOURCE=multitasking.c timer.c tss.c scheduler.c sleep.c
ASM_SOURCE=pit.asm mutex.asm

INTEGRATION_TEST_C_SOURCE=mutex_test.c

include ../settings.mk
include ../kernel.mk

pit.asm : multitasking.mac
